import NEWS_EXTRACTOR
import PUBLICATION_EXTRACTOR
import PRESSRELEASE_EXTRACTOR
import TRIGGERING_NEWSLETTER

# EXTRATION OF THE NEW ARTICLE FROM THE 3 WEB PAGES OF BPS
NEWS_EXTRACTOR.extract_news()
PUBLICATION_EXTRACTOR.publication_extract()
PRESSRELEASE_EXTRACTOR.pressrelease_extract()

# FINDING USERS TO NOTIFY AND THEN SEND EMAIL
TRIGGERING_NEWSLETTER.trigger_and_mail()
